# Generated by Django 5.2.5 on 2025-08-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=40, unique=True)),
                ("password", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=30)),
                ("zip", models.IntegerField(default=0)),
            ],
        ),
    ]
