# Generated by Django 5.2.5 on 2025-08-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spc_id", models.CharField(max_length=100)),
                ("user", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="ItemCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=40)),
                ("active", models.BooleanField(default=False)),
                ("product", models.CharField(max_length=40)),
                ("product_quantity", models.IntegerField(default=0)),
                ("product_price", models.IntegerField(default=0)),
                ("total_cart_value", models.IntegerField(default=0)),
                ("product_image", models.ImageField(upload_to="")),
                ("slug", models.CharField(default=None, max_length=40)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.sessioncart",
                    ),
                ),
            ],
        ),
    ]
