# Generated by Django 5.2.5 on 2025-08-15 14:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_sessioncart_itemcart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcart",
            name="product_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
